stages:
  - before_all_scripts
  - test
  - docu
  - after_all_scripts

cache:
  paths:
    - coverage_report

default:
  before_script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python
  after_script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python

run_before_all_scripts:
  stage: before_all_scripts
  script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python
#    - pip3 install cfchecker
#    - pip3 install sphinx-jsonschema
    - ./install2home

run_after_all_scripts:
  stage: after_all_scripts
  script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python
    - pwd
    - cat installed_files.txt | xargs rm -rf
    - rm installed_files.txt
    - rm -r build doc/build

pytest_coverage:
  stage: test
  script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python
    - env python3 setup.py run_pytest --coverage
    - sleep 3

unittest:
  stage: test
  script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python
    - env python3 setup.py run_unittest

pages:
  stage: docu
  needs: ["pytest_coverage"]
  script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python
    - ./create_doc_html
    - rsync --archive --delete-after --one-file-system --links --hard-links --sparse --checksum manual_pydabu_html/ public/
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \;
#    - pip3 install anybadge
    - anybadge -l " " -v documentation -f documentation.svg -c fuchsia -o

  artifacts:
    paths:
      - public
      - documentation.svg
  only:
    - master
