stages:
  - test
  - docu

default:
  before_script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python
#    - pip3 install cfchecker
#    - pip3 install sphinx-jsonschema
    - ./install2home
  after_script:
    - cat installed_files.txt | xargs rm -rf
    - rm installed_files.txt
#    - pip3 install anybadge
    - anybadge -l " " -v documentation -f documentation.svg -c fuchsia -o
    - rm -r build doc/build coverage_report

pytest_coverage:
  stage: test
  script:
    - env python3 setup.py run_pytest --coverage

pages:
  stage: docu
  needs: ["pytest_coverage"]
  script:
    - ./create_doc_html
    - rsync --archive --delete-after --one-file-system --links --hard-links --sparse --checksum manual_pydabu_html/ public/
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \;

  artifacts:
    paths:
      - public
      - documentation.svg
  only:
    - master
