default:
  before_script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python
#    - pip3 install cfchecker
    - ./install2home
  after_script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python
    - cat installed_files.txt | xargs rm -rf
    - rm installed_files.txt
#    - pip3 install anybadge
    - anybadge -l " " -v documentation -f documentation.svg -c fuchsia -o
    - rm -r build doc/build

pages:
  script:
    - export PATH=$PATH:~/bin:~/.local/bin
    - export PYTHONPATH=$PYTHONPATH:~/lib/python
    - ./create_doc_html
    - rsync --archive --delete-after --one-file-system --links --hard-links --sparse --checksum manual_pydabu_html/ public/

  artifacts:
    paths:
      - public
      - documentation.svg
  only:
    - master
